// Code generated by mockery v2.26.1. DO NOT EDIT.

package mocks

import (
	context "context"

	golibvirt "libvirt.org/go/libvirt"

	mock "github.com/stretchr/testify/mock"
)

// Domain is an autogenerated mock type for the Domain type
type Domain struct {
	mock.Mock
}

// AmplifyVolume provides a mock function with given fields: filepath, cap
func (_m *Domain) AmplifyVolume(filepath string, cap uint64) error {
	ret := _m.Called(filepath, cap)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, uint64) error); ok {
		r0 = rf(filepath, cap)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AttachVolume provides a mock function with given fields: xml
func (_m *Domain) AttachVolume(xml string) (golibvirt.DomainState, error) {
	ret := _m.Called(xml)

	var r0 golibvirt.DomainState
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (golibvirt.DomainState, error)); ok {
		return rf(xml)
	}
	if rf, ok := ret.Get(0).(func(string) golibvirt.DomainState); ok {
		r0 = rf(xml)
	} else {
		r0 = ret.Get(0).(golibvirt.DomainState)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(xml)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields:
func (_m *Domain) Create() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Destroy provides a mock function with given fields:
func (_m *Domain) Destroy() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DestroyFlags provides a mock function with given fields: flags
func (_m *Domain) DestroyFlags(flags golibvirt.DomainDestroyFlags) error {
	ret := _m.Called(flags)

	var r0 error
	if rf, ok := ret.Get(0).(func(golibvirt.DomainDestroyFlags) error); ok {
		r0 = rf(flags)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Free provides a mock function with given fields:
func (_m *Domain) Free() {
	_m.Called()
}

// GetInfo provides a mock function with given fields:
func (_m *Domain) GetInfo() (*golibvirt.DomainInfo, error) {
	ret := _m.Called()

	var r0 *golibvirt.DomainInfo
	var r1 error
	if rf, ok := ret.Get(0).(func() (*golibvirt.DomainInfo, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *golibvirt.DomainInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*golibvirt.DomainInfo)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetName provides a mock function with given fields:
func (_m *Domain) GetName() (string, error) {
	ret := _m.Called()

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetState provides a mock function with given fields:
func (_m *Domain) GetState() (golibvirt.DomainState, error) {
	ret := _m.Called()

	var r0 golibvirt.DomainState
	var r1 error
	if rf, ok := ret.Get(0).(func() (golibvirt.DomainState, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() golibvirt.DomainState); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(golibvirt.DomainState)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUUIDString provides a mock function with given fields:
func (_m *Domain) GetUUIDString() (string, error) {
	ret := _m.Called()

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetXMLDesc provides a mock function with given fields: flags
func (_m *Domain) GetXMLDesc(flags golibvirt.DomainXMLFlags) (string, error) {
	ret := _m.Called(flags)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(golibvirt.DomainXMLFlags) (string, error)); ok {
		return rf(flags)
	}
	if rf, ok := ret.Get(0).(func(golibvirt.DomainXMLFlags) string); ok {
		r0 = rf(flags)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(golibvirt.DomainXMLFlags) error); ok {
		r1 = rf(flags)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QemuAgentCommand provides a mock function with given fields: ctx, cmd, flags
func (_m *Domain) QemuAgentCommand(ctx context.Context, cmd string, flags uint32) (string, error) {
	ret := _m.Called(ctx, cmd, flags)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint32) (string, error)); ok {
		return rf(ctx, cmd, flags)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uint32) string); ok {
		r0 = rf(ctx, cmd, flags)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uint32) error); ok {
		r1 = rf(ctx, cmd, flags)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Resume provides a mock function with given fields:
func (_m *Domain) Resume() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetMemoryFlags provides a mock function with given fields: memory, flags
func (_m *Domain) SetMemoryFlags(memory uint64, flags golibvirt.DomainMemoryModFlags) error {
	ret := _m.Called(memory, flags)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, golibvirt.DomainMemoryModFlags) error); ok {
		r0 = rf(memory, flags)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetVcpusFlags provides a mock function with given fields: vcpu, flags
func (_m *Domain) SetVcpusFlags(vcpu uint, flags golibvirt.DomainVcpuFlags) error {
	ret := _m.Called(vcpu, flags)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, golibvirt.DomainVcpuFlags) error); ok {
		r0 = rf(vcpu, flags)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ShutdownFlags provides a mock function with given fields: flags
func (_m *Domain) ShutdownFlags(flags golibvirt.DomainShutdownFlags) error {
	ret := _m.Called(flags)

	var r0 error
	if rf, ok := ret.Get(0).(func(golibvirt.DomainShutdownFlags) error); ok {
		r0 = rf(flags)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Suspend provides a mock function with given fields:
func (_m *Domain) Suspend() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UndefineFlags provides a mock function with given fields: flags
func (_m *Domain) UndefineFlags(flags golibvirt.DomainUndefineFlagsValues) error {
	ret := _m.Called(flags)

	var r0 error
	if rf, ok := ret.Get(0).(func(golibvirt.DomainUndefineFlagsValues) error); ok {
		r0 = rf(flags)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewDomain interface {
	mock.TestingT
	Cleanup(func())
}

// NewDomain creates a new instance of Domain. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDomain(t mockConstructorTestingTNewDomain) *Domain {
	mock := &Domain{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
